select *from CUSTOMER

-- SELECTION OF ATTRIBUTES
SELECT DISTINCT CUST_NAME       -- DISTINCT will print all unique values.
SELECT ALL CUST_NAME            -- ALL will print all values of an ATTRIBUTE.
-- SELECTION OF TABLE
FROM CUSTOMER;


-- CONDITION
SELECT "CUST_NAME"
FROM CUSTOMER
WHERE "CUS_CODE"='C00013'


-- CONITION [OPTIONAL]
SELECT DISTINCT "CUST_CITY"
FROM CUSTOMER


SELECT DISTINCT CUST_CITY, CUST_NAME
FROM CUSTOMER

