--  LIKE CLAUSE
--      1. %
--      2. _ (underscore)

-- TO SEARCH FOR AN ARRTIBUTE'S VALUE WHERE FIRST FIRST LETTER OF THE VALUE IS 'S'
SELECT* FROM CUSTOMER
WHERE CUST_NAME LIKE 'S%'

-- WE CAN ALSO DO THIS:
SELECT* FROM CUSTOMER
WHERE CUST_NAME LIKE 'St%'

-- WE CAN ALSO DO THIS:
-- IF WE WANT TO SEARCH WHOLE NAME, WE DONT HAVE TO PUT % SIGN. BUT IF WE WANT, WE CAN STILL PUT % SYMBOL
SELECT* FROM CUSTOMER
WHERE CUST_NAME LIKE 'Steven'
